import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {SOURCE_HASH,seedModel,validateModel,wallPanels,traceToFeet,feetToTrace,traceToPage} from './model.mjs';
const $=id=>document.getElementById(id), FT=.3048, key='liquid-build-studio:'+SOURCE_HASH;
let model=seedModel(), history=[], selected='south-living', cutaway=false, labels=true, group, renderer, controls, camera, sourceZoom=1, pending=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e7ece7');
const status=(s,error=false)=>{$('message').textContent=s;$('message').dataset.error=String(error);};
const materials={wall:new THREE.MeshStandardMaterial({color:'#f8f5eb',roughness:.85}),selected:new THREE.MeshStandardMaterial({color:'#df9b54'}),glass:new THREE.MeshStandardMaterial({color:'#81bac4',transparent:true,opacity:.4,roughness:.15}),slab:new THREE.MeshStandardMaterial({color:'#abb6ac'})};
function box(parent,w,h,d,x,y,z,material,wallId){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w*FT,h*FT,d*FT),material);mesh.position.set(x*FT,y*FT,z*FT);mesh.castShadow=true;mesh.receiveShadow=true;if(wallId)mesh.userData.wallId=wallId;parent.add(mesh);return mesh;}
function makeModel(m,cut=false,highlight=false){
 const root=new THREE.Group();root.name='311 ground floor — approximate manual trace';root.userData={sourceHash:m.sourceHash,sourcePage:11,units:'meters',revision:m.revision,assumptions:m.assumptions,constructionReady:false};
 // Slab follows the stepped footprint. Room fills remain a reference layer.
 const outline=[[319,466],[1755,466],[1755,860],[1338,860],[1338,891],[1068,891],[1068,860],[319,860]].map(traceToFeet);
 const shape=new THREE.Shape();outline.forEach(([x,z],i)=>i?shape.lineTo(x*FT,-z*FT):shape.moveTo(x*FT,-z*FT));shape.closePath();
 const slab=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.5*FT,bevelEnabled:false}),materials.slab);slab.rotation.x=-Math.PI/2;slab.position.y=-.5*FT;slab.receiveShadow=true;root.add(slab);
 for(const room of m.rooms){const [x,z]=traceToFeet(room.rect.slice(0,2)),[xx,zz]=traceToFeet(room.rect.slice(2));box(root,xx-x,.08,zz-z,(x+xx)/2,.045,(z+zz)/2,new THREE.MeshStandardMaterial({color:room.color,roughness:.9}));}
 for(const w of m.walls){
 const g=new THREE.Group();g.name=w.label;g.position.set(w.a[0]*FT,0,w.a[1]*FT);g.rotation.y=-Math.atan2(w.b[1]-w.a[1],w.b[0]-w.a[0]);root.add(g);
 for(const p of wallPanels(w,m.assumptions.wallHeight)){const h=Math.min(p.height,(cut?3.5:m.assumptions.wallHeight)-p.y);if(h>0)box(g,p.width,h,m.assumptions.wallThickness,p.x+p.width/2,p.y+h/2,0,highlight&&w.id===selected?materials.selected:materials.wall,w.id);}
 for(const o of w.openings){if(o.type==='window'&&!cut)box(g,o.width,o.top-o.sill,.07,o.at,(o.sill+o.top)/2,0,materials.glass,w.id);}
 }
 return root;
}
function dispose(g){g.traverse(o=>{o.geometry?.dispose();if(o.material&&!Object.values(materials).includes(o.material))o.material.dispose();});}
function draw(){if(pending||!renderer)return;pending=true;requestAnimationFrame(()=>{pending=false;renderer.render(scene,camera);document.querySelectorAll('.room-label').forEach(el=>{const p=new THREE.Vector3(...JSON.parse(el.dataset.position)).project(camera);el.style.left=(p.x*.5+.5)*$('scene').clientWidth+'px';el.style.top=(-p.y*.5+.5)*$('scene').clientHeight+'px';el.hidden=!labels||p.z>1;});$('metrics').dataset.geometries=renderer.info.memory.geometries;});}
function rebuild(){if(group){scene.remove(group);dispose(group);}group=makeModel(model,cutaway,true);scene.add(group);$('scene').dataset.height=model.assumptions.wallHeight;$('scene').dataset.revision=model.revision;trace();draw();$('model-caption').textContent=`One floor · no roof · ${model.assumptions.wallHeight} ft wall height assumed${cutaway?' · cutaway at 3.5 ft':''}`;$('metrics').textContent=`${model.walls.length} walls · ${model.walls.reduce((n,w)=>n+w.openings.length,0)} openings · revision ${model.revision}`;}
function trace(){const svg=$('trace');svg.replaceChildren();for(const w of model.walls){const a=feetToTrace(w.a),b=feetToTrace(w.b),line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v] of Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1],'data-wall':w.id,stroke:w.id===selected?'#12624e':'#e28a34','stroke-width':w.id===selected?6:3}))line.setAttribute(k,v);line.addEventListener('click',()=>select(w.id));svg.append(line);}}
function select(id){selected=id;$('wall').value=id;const w=model.walls.find(w=>w.id===id);['ax','az','bx','bz'].forEach((id,i)=>{$(id).value=[...w.a,...w.b][i].toFixed(3);});$('wall-state').textContent=`${Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1]).toFixed(1)} ft · ${w.edited?'edited locally':'approximate manual trace'}`;$('opening').replaceChildren(...w.openings.map(o=>new Option(`${o.type} · ${o.id}`,o.id)));openingFields();rebuild();}
function openingFields(){const w=model.walls.find(w=>w.id===selected),o=w.openings.find(o=>o.id===$('opening').value);for(const id of ['opening','opening-at','opening-width','apply-opening'])$(id).disabled=!o;$('opening-at').value=o?.at??'';$('opening-width').value=o?.width??'';}
function sync(){ $('height').value=model.assumptions.wallHeight;$('height-value').textContent=model.assumptions.wallHeight.toFixed(1)+' ft';$('thickness').value=model.assumptions.wallThickness;$('thickness-value').textContent=(model.assumptions.wallThickness*12).toFixed(1)+' in';$('undo').disabled=!history.length;select(selected);}
function commit(edit){try{const next=structuredClone(model);edit(next);validateModel(next);history.push(structuredClone(model));if(history.length>30)history.shift();next.revision=model.revision+1;model=next;sync();status('Model updated in your browser. Save locally to keep these edits.');}catch(e){status(e.message,true);sync();}}
function frame(top=false){const bounds=new THREE.Box3().setFromObject(group),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const distance=Math.max(size.x/camera.aspect,size.z)*1.2+8;controls.target.set(center.x,0,center.z);camera.position.copy(controls.target).add(top?new THREE.Vector3(0,distance,.001):new THREE.Vector3(distance*.18,distance*.85,distance*.85));camera.up.set(0,1,0);controls.enableRotate=!top;controls.update();$('top').classList.toggle('selected',top);$('orbit').classList.toggle('selected',!top);draw();}
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function resizeSource(){const width=Math.max(280,$('source-scroll').clientWidth-28)*sourceZoom;$('source-sheet').style.width=width+'px';}
async function init(){
 try{
 const response=await fetch('/sample.pdf');if(!response.ok)throw Error('Start the viewer with the 311 SW 14 CT PDF to load this prototype.');const bytes=await response.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==SOURCE_HASH)throw Error('The sample PDF does not match this trace. Open the original 311 SW 14 CT plan.');
 try{const saved=localStorage.getItem(key);if(saved)model=validateModel(JSON.parse(saved));}catch{status('Saved model could not be loaded; restored the original trace.');}
 const pdfjs=await import('/vendor/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/build/pdf.worker.mjs';const loadingTask=pdfjs.getDocument({data:bytes,cMapUrl:'/vendor/cmaps/',cMapPacked:true,standardFontDataUrl:'/vendor/standard_fonts/',wasmUrl:'/vendor/wasm/'});const pdf=await loadingTask.promise;const page=await pdf.getPage(11),scale=1.5,viewport=page.getViewport({scale});const full=document.createElement('canvas');full.width=viewport.width;full.height=viewport.height;await page.render({canvasContext:full.getContext('2d'),viewport}).promise;
 const crop=[130,435,1910,980],a=traceToPage(crop.slice(0,2)),b=traceToPage(crop.slice(2)),canvas=$('source-canvas');canvas.width=(b[0]-a[0])*scale;canvas.height=(b[1]-a[1])*scale;canvas.getContext('2d').drawImage(full,a[0]*scale,a[1]*scale,canvas.width,canvas.height,0,0,canvas.width,canvas.height);$('trace').setAttribute('viewBox',`${crop[0]} ${crop[1]} ${crop[2]-crop[0]} ${crop[3]-crop[1]}`);await loadingTask.destroy();full.width=full.height=0;
 renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('scene').prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D model rendered locally with WebGL');camera=new THREE.PerspectiveCamera(40,1,.1,500);controls=new OrbitControls(camera,renderer.domElement);controls.maxPolarAngle=Math.PI/2-.05;controls.minDistance=3;controls.maxDistance=100;controls.addEventListener('change',draw);
 scene.add(new THREE.HemisphereLight(0xffffff,0xabb7a2,1.6));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(8,25,12);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-30,right:30,top:30,bottom:-30});light.shadow.bias=-.001;scene.add(light);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#e7ece7'}));ground.rotation.x=-Math.PI/2;ground.position.y=-.17;ground.receiveShadow=true;scene.add(ground);
 for(const r of model.rooms){const a=traceToFeet(r.rect.slice(0,2)),b=traceToFeet(r.rect.slice(2)),el=document.createElement('span');el.className='room-label';el.textContent=r.label;el.dataset.position=JSON.stringify([(a[0]+b[0])/2*FT,.2,(a[1]+b[1])/2*FT]);$('room-labels').append(el);}
 $('wall').replaceChildren(...model.walls.map(w=>new Option(w.label,w.id)));sync();const resize=()=>{const el=$('scene');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();resizeSource();if($('scene').dataset.ready)frame($('top').classList.contains('selected'));draw();};new ResizeObserver(resize).observe($('scene'));resize();frame();
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObject(group,true).find(h=>h.object.userData.wallId);if(hit)select(hit.object.userData.wallId);});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status('Graphics context lost. Reload to restore the 3D view; saved edits remain on this device.',true);});
 document.querySelectorAll('button,input,select').forEach(el=>el.disabled=false);sync();$('renderer-label').textContent='WebGL · local GPU';$('scene').dataset.ready='true';$('export-glb').disabled=false;status('Ready · manually traced from your PDF. Heights and openings are approximate.');
 }catch(e){status('Could not start studio: '+e.message,true);$('renderer-label').textContent='Unavailable';console.error(e);}
}
$('wall').onchange=()=>select($('wall').value);$('opening').onchange=openingFields;
$('height').onchange=()=>commit(m=>m.assumptions.wallHeight=Number($('height').value));$('thickness').onchange=()=>commit(m=>m.assumptions.wallThickness=Number($('thickness').value));
$('apply-wall').onclick=()=>commit(m=>{const w=m.walls.find(w=>w.id===selected);w.a=[Number($('ax').value),Number($('az').value)];w.b=[Number($('bx').value),Number($('bz').value)];w.edited=true;});
$('apply-opening').onclick=()=>commit(m=>{const w=m.walls.find(w=>w.id===selected),o=w.openings.find(o=>o.id===$('opening').value);o.at=Number($('opening-at').value);o.width=Number($('opening-width').value);o.provenance='user_edited';w.edited=true;});
$('undo').onclick=()=>{if(history.length){model=history.pop();sync();status('Undid the last model edit.');}};
$('reset-model').onclick=()=>commit(m=>Object.assign(m,seedModel()));
$('save').onclick=()=>{try{localStorage.setItem(key,JSON.stringify(model));status('Saved on this browser and device. Export JSON for a portable copy.');}catch(e){status('Could not save locally: '+e.message,true);}};
$('export-json').onclick=()=>download(JSON.stringify(model,null,2),'application/json','311-ground-floor-model.json');
$('export-glb').onclick=async()=>{let exportGroup;try{$('export-glb').disabled=true;exportGroup=makeModel(model);exportGroup.updateMatrixWorld(true);const bytes=await new GLTFExporter().parseAsync(exportGroup,{binary:true});download(bytes,'model/gltf-binary','311-ground-floor-concept.glb');status('Exported full-height GLB in meters, including source and assumption metadata.');}catch(e){status('Export failed: '+e.message,true);}finally{if(exportGroup)dispose(exportGroup);$('export-glb').disabled=false;}};
$('top').onclick=()=>frame(true);$('orbit').onclick=()=>frame(false);$('reset-camera').onclick=()=>frame(false);
$('cutaway').onclick=()=>{cutaway=!cutaway;$('cutaway').setAttribute('aria-pressed',cutaway);rebuild();};$('labels').onclick=()=>{labels=!labels;$('labels').setAttribute('aria-pressed',labels);$('labels').textContent=labels?'Labels on':'Labels off';draw();};
$('source-plus').onclick=()=>{sourceZoom=Math.min(5,sourceZoom*1.4);resizeSource();};$('source-minus').onclick=()=>{sourceZoom=Math.max(1,sourceZoom/1.4);resizeSource();};$('trace-toggle').onclick=()=>{const hidden=$('trace').style.display==='none';$('trace').style.display=hidden?'':'none';$('trace-toggle').textContent=hidden?'Trace on':'Trace off';$('trace-toggle').setAttribute('aria-pressed',hidden);};
document.querySelectorAll('button,input,select').forEach(el=>el.disabled=true);
init();
